name = "CommandLineEquationsOfState"
uuid = "0199c5d7-4cc5-426e-b3a3-97474e9b93b8"
authors = ["Qi Zhang <singularitti@outlook.com>"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
